### ISSUE TITLE
[Search] Improvements

### ISSUE THREAD

**Issue by ponceta** [geoadmin/mf-geoadmin3#2170]
This summaries a bit what is expected to be improved on geoadmin search

 - [ ]  "Zolliker Strasse“ has to find „Zollikerstrasse“ (#1860)
 - [x] "Hallenstadion" has to find "Hallen stadion" (#1859)
 - [x] "Birgmattenweg" has to find "Brigmattenweg"
 - [x] Add a "did you mean" message before fuzzy search results (#1910)
 - [x] Improve ranking of fuzzy search (#1910)
 - [x] äbnit (BE) search result not always the same (#2062)

See also [This doc](https://docs.google.com/spreadsheets/d/1IHZvD9JyNHgoeqfy_Rb1eNzhSIusd4a5hvDlm0Dcq6w/edit#gid=0) for reference queries

**Comment by davidoesch** [comment]
"Zolliker Strasse“ has to find „Zollikerstrasse“ (#1860) issue will be solved as soon as more than 50 datasets are displayed in the results.... depending on the decision by the ct. @beat-github  what is teh current status regarding addresses?
