### ISSUE TITLE
Import: Redesign

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2414]
based on the design/usability feedback

One Import widget
- [ ] See geocat feed #3023
online ressources
- [ ] one TAB for ONLINE sources
  - [x] WMS 
    - [ ] WMS with Auth (manage permalink -> no pwd in permalink / ask user/pwd at start)
    - [x] GetFeatureInfo with TXT format
  - [x] WMTS
    - [ ] WMTS with Auth (manage permalink -> no pwd in permalink / ask user/pwd at start)
      Pulldown content
  - [ ] provide a github based config file to add, change and delete and translate title for the URL Links, based on a google spreadsheet based approach similar as for the translation.Variables see https://docs.google.com/spreadsheets/d/1Lg3BrJ_FHaUddFAL7-QzeJrxQ2lLwRMgLqImyugariA/edit?usp=sharing see as well geocat https://github.com/geoadmin/mf-geoadmin3/issues/2414
    - source id (eg 1)
    - URL to getCap ( eg http://wms.geo.admin.ch/?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.0.0&lang=de)
    - Copyright Text ( Geoportal Bund)
    - Copyright URL ( www.geo.admin.ch)
    - DE (eg. wms.geo.admin.ch)
    - FR (eg. wms.geo.admin.ch)
    - IT (eg. wms.geo.admin.ch)
    - EN (eg. wms.geo.admin.ch)
  - [x] add existing WMS pulldown content
  - [x] WM(T)S with other projections (#2773)
    - [x] DE BW_ according to list in  http://rips-dienste.lubw.baden-wuerttemberg.de/rips/ripsservices/apps/uis/metadaten/suche.aspx?suche=infoMapAccessService   - DE BW http://www.webatlasde.de/arcgis/services/Maps4BW/MapServer/WMSServer?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
    - [x] DE BAyern: according to list in http://vermessung.bayern.de/opendata 
    - [ ] FR Cadastre: according to https://www.cadastre.gouv.fr/scpc/pdf/Guide_WMS_fr.pdf for all border communes http://inspire.cadastre.gouv.fr/scpc/[codeINSEE].wms?service=WMS&request=GetCapabilities&
      replace [codeINSEE] according to http://www.insee.fr/fr/methodes/nomenclatures/cog/ 
    - [x] AU Basemap http://www.basemap.at/wmts/1.0.0/WMTSCapabilities.xml 
    - [ ]  add all non swiss projected sources mentionend and tested in https://github.com/geoadmin/mf-geoadmin3/pull/2917#issuecomment-158026499
    - [ ]  https://www.so.ch/verwaltung/bau-und-justizdepartement/amt-fuer-  
    - [ ]  geoinformation/geoportal/geodienste/wmts-web-map-tile-service/
    - [ ]  http://www.zg.ch/behoerden/direktion-des-innern/geoportal/geodaten-einbinden/web-map-tile-service-wmts
    - [ ]  http://www.gis.stadt-zuerich.ch/wmts/wmts-zh-stzh-ogd.xml  
    - [ ]  http://www.catais.org/mapcache/wmts/1.0.0/WMTSCapabilities.xml
    - [ ]  http://www.catais.org/mapcache/wmts?service=wmts&request=getcapabilities&version=1.0.0
    - [ ]  http://cidportal.jrc.ec.europa.eu/copernicus/services/tile/wmts/1.0.0/WMTSCapabilities.xml

local  ressources
- [x] one TAB for LOCAL sources
  - [x] KML,KMZ
  - [x] GPX, to replace SMO and support http://swissmapconverter.ch/ for import
  - [ ] when importing KML  -> set flag for store in public.geo.admin.ch  , if file is not bigger than 2MB
  - [ ] SketchUP  import https://github.com/KhronosGroup/glTF/issues/1058#issuecomment-322887603 

Optional:
- [ ] Check imported files for compliance, if there are "serious" errors on the file/URL show/display a message WHY file can not be shown
- [ ] httpauth for WMS WMTS Services
- [ ] http://cite.opengeospatial.org/teamengine/ for KML, WMS , WMTS
- [ ]  eCH-0056: Geoservices Application Profile WMS WMTS http://api3.geo.admin.ch/services/sdiservices.html#owschecker-check-conformity-with-ech-0056 

Mockup see https://docs.google.com/presentation/d/1yR3kYfduTsEO3koIFFe2pdXCYIcSA1eWs6a4n0dIFQ0/edit#slide=id.ge9ace91ee_0_41 

related tickets #2301 #1654 , #2773

**Comment by gjn** [comment]
For the configuration, I would propse a json file inside the project.

But updaters would need to learn to work with git/github process.

**Comment by gjn** [comment]
@davidoesch Since new import dialog is released, we need to rediscuss this issue and re-prioritize it.

**Comment by davidoesch** [comment]
Yep. Let's brainstorm this 1:1.

**Comment by Jenselme** [comment]
My PR about WMTS import was merged into ngeo: https://github.com/camptocamp/ngeo/pull/2543 We are already using this code to import WMTS servers in our fork. Would you be interested that I port our changes, update ngeo in the Makefile and create a PR for WMTS import in mf-geoadmin3? If so, do you have a list of WMTS servers you want to import with the list of servers?

**Comment by davidoesch** [comment]
See list in the ticket description: there are a lot of wmts sources (since ticket is quite old... Some of them might have stopped working)

**Comment by oterral** [comment]
Of course @Jenselme your PRs are always welcome!!

**Comment by Jenselme** [comment]
@davidoesch OK. From the list, I have these WMTS server that are still working:
- AU Basemap http://www.basemap.at/wmts/1.0.0/WMTSCapabilities.xml
- WMTS from https://www.zg.ch/behoerden/direktion-des-innern/geoportal/geodaten-einbinden/web-map-tile-service-wmts
- http://www.gis.stadt-zuerich.ch/wmts/wmts-zh-stzh-ogd.xml
- http://cidportal.jrc.ec.europa.eu/copernicus/services/tile/wmts/1.0.0/WMTSCapabilities.xml

I'll use them as default sources to start.

@oterral ^^

**Comment by gjn** [comment]
+1 @Jenselme !

**Comment by gjn** [comment]
@Ariadnigaki will test which WMTS in the list of the OP work in the current import, also, she will test which of those can be printed out.

**Comment by procrastinatio** [comment]
WMTS + BasicAuth: it's works as long as your WMS server support CORS/Head requests/HTTPS (i.e. map.geo.admin.ch does not need to use proxy).

If we have to use proxy, no way to ask user for username/password...

**Comment by Ariadnigaki** [comment]
The following WMTS are working in the current import:

-  AU Basemap http://www.basemap.at/wmts/1.0.0/WMTSCapabilities.xml
-  http://www.gis.stadt-zuerich.ch/wmts/wmts-zh-stzh-ogd.xml
-  http://cidportal.jrc.ec.europa.eu/copernicus/services/tile/wmts/1.0.0/WMTSCapabilities.xml

There is an error during the import of https://www.zg.ch/behoerden/direktion-des-innern/geoportal/geodaten-einbinden/web-map-tile-service-wmts

In addition, when i tried to print them out, the following error was presented:

POST https://print.geo.admin.ch/print/create.jsonurl=https%3A%2F%2Fprint.geo.admin.ch%2Fprint%2Fcreate.json 500 (Internal Server Error)

**Comment by boecklic** [comment]
will be solved within scope of https://github.com/geoadmin/mf-geoadmin3/issues/4668
