### ISSUE TITLE
Draw v2

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2467]
Improvement
- [x] Share procedure (How to inform about the share links) ?

Code:

- [x]  ~~Use Mapfish V3 for SVG icons and text's stroke ?~~ v3 migration abandoned
- [x]  Use color service (2nd possibility in https://github.com/geoadmin/mf-geoadmin3/issues/2618)
- [x]  Use at least ol [3.7](https://github.com/openlayers/ol3/releases) for : 
            - https://github.com/openlayers/ol3/pull/3461
            - https://github.com/openlayers/ol3/pull/3635
            - https://github.com/openlayers/ol3/pull/3766
- [x]  Refactoring of the draw events callbacks
- [x]  Refactoring/rename the togglePopup stuff
- [x]  Clean the dropdown toggle hack
- [x]  Verify if `ga-draw-info-save`  and `.ga-draw-disclaimer ` use a CD bund color
- [ ]  Warn the user or us when a file save has failed?
- [ ]  ~~Use a map property in profile ?~~ 
- [ ]  ~~Hide menu when drawing ?~~

New tools:

- [ ]  ~~Rectangle~~
- [ ]  ~~Circle~~

New styles:

- [ ]  ~~Stroke width of polygon and line~~
- [x]  Size of text including a carriage return **(prio1)**
- [x]  Color of icon  **(prio1)**
- [ ]  ~~Color of text background  **(prio1)**~~
- [x]  Symbol & description text shown at the same (checkbox)**(prio1)**

New functionalties:

- [x]  Delete last point
- [ ]  Continue a line / measure after saving
- [ ]  Undo/redo  ?
- [x]  Add a button to delete the current feature selected 
- [ ]  Enter multiple symbols in a row without having to click each time a button (use case: the guy who wants to mark a route with points )
- [ ]  ~~On small screen dropdown menu of  `more` button is hidden~~Menu removed
- [ ]  Set the "Name" of the layer, and use it as kml export name as well
- [ ]  ~~Embed in more button "embed into my site"~~Share stuff moved in modal
- [ ]  Keep the last style used for the next one
- [x] Enhance profile as described in https://github.com/geoadmin/mf-geoadmin3/issues/1912 
- [ ] show length of vector while drawing as in measure (user suggestion)
- [ ] GPX Support as in https://github.com/geoadmin/mf-geoadmin3/issues/2301
- [ ] magnetic drawing based on ve25 : to be confirmed by TOPO
- [x] Profile of imported KML /GPX
- [x] show sum of profile
- [x] ~~show begin (Start) and end (Ziel ) of ameasurement with a ballon **(prio1)**~~Show intermediate measures
- [ ] ~~option to toggle on/off « Information objet » et «Drawing  for pop up~~
- [x]  line of sight in profile (inlc distance)
- [ ] Profile: enable print see #1912 
- [x] Profile: enable resize ( better for scrresnhots/prints of flat areas)

Hold/open points:
- [ ]  Feature list in accordeon
- [x]  ~~Showing a link between an object and an object box with a line or fit it to image~~Popup appears close to the feature selected
- [ ] mobile draw

**Comment by davidoesch** [comment]
@oterral  since you are working on this, solve for now only the open prio1 
 Size of text ibcluding a carriage return (prio1)
 Color of text (prio1)
 Color of text background (prio1)
 Symbol & description text shown at the same (checkbox)(prio1)
show begin (Start) and end (Ziel ) of ameasurement with a ballon (prio1)

then we look at the next points

**Comment by oterral** [comment]
@davidoesch What do youe mean by "Color of text", we already have it no?

**Comment by davidoesch** [comment]
we already have it, already set to ok

**Comment by oterral** [comment]
> Symbol & description text shown at the same (checkbox)(prio1)

Something like [that](https://mf-geoadmin3.dev.bgdi.ch/teo_draw/src/?lang=fr&topic=aviation&bgLayer=ch.swisstopo.pixelkarte-grau&X=214000.00&Y=705500.00&dev3d=true&zoom=1&debug&catalogNodes=1379,1514&layers=&adminId=yHhcRXfLTQC5w_xytJgxrQ) or eeally only a checkbox under description

**Comment by davidoesch** [comment]
yes like this, text below (south) ( label/description) tag

**Comment by oterral** [comment]
> Color of text background (prio1)

Do you mean the stroke of the text or a rectangular background behind the text.  The 2nd option is tricky because there is not KML support for this and so, no print support.

**Comment by davidoesch** [comment]
it is the latter (rectangular background behind the text) ---comination with a rectangle? even add to features? or make a huge border aroudn teh text?

**Comment by davidoesch** [comment]
@oterral Color of text (prio1) was actually color of icon

**Comment by gjn** [comment]
ha!
