### ISSUE TITLE
Go Live ALPHA: roadmap

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2954]
Mission target ALPHA

* 2D no downtime 
* costs: if estimated 3D costs per month go above 5kUS$* shut down 3D 

- [x] nasty Questions  currently approved by KOMM @davidoesch
- [x] 2.5D button @pfanguin 
- [x] swissimage warning text  @oterral  
- [x] autoscaling backend max 30 instances @procrastinatio  
- [x] push / mail / controlling of daily AWS costs @hpchrist 
- [x] push / mail / pingdom/ load on back end @hpchrist 
- [x] acceptance protocol terrain signed @mariokeusen 
- [x] acceptance protocol 2.5D signed @mariokeusen 
- [x]  no first prio 1 3d tix open https://github.com/geoadmin/mf-geoadmin3/labels/1st%20prio
- [x] help updated @pfanguin 
- [x] WMS: add 2 new instances @danduk82  
- [x] VPC endpoint routing @danduk82 
- [x] LayersConfig @loicgasser @ltclm
- [x] Optimized BG layers (size reduction) @ltclm 
- [x] 2.5D activated by default @gjn 
- [x] deploy version on 11.12.2015 @gjn 
- [x] terrain doc @loicgasser 
- [x] remove offline button when I'm 3D @oteral  (wait merge of #2989)
- [x] layer attribution for new 3D layers @oterral (wait merge of #2987)
- [x] Dashboard WMTS:  https://logs.bgdi.ch/kibana/#/dashboard/elasticsearch/traffic%203D
- [x] Dashboard MAPPROXY https://share.pingdom.com/banners/91d47e31 and https://my.pingdom.com/reports/uptime#check=1902106&tab=responsetime_tab&daterange=1days 
- [x] Grafana: Dashboard: AWS Network @danduk82  
- [x] Grafana: Dashboard: WMS @danduk82  
- [x] Dashboard: AWS Console  ELB @danduk82  
- [x] architecture schema @danduk82 https://doc.prod.bgdi.ch/wmts.html
- [x] 2 snapshots with/without 2.5D @gjn  
- [x] testing on  monday @davidoesch : https://docs.google.com/spreadsheets/d/14n3JYNL-4ACiqExUeoqqbHmWmqtfq2BB-qC21Beb6Dw/edit?pli=1#gid=737839311 
- [x] 2 varnish instances + 1 Fallback instance@danduk82  
- [x] emergency scenarios / rollback scenario @gjn @cedricmoullet https://docs.google.com/spreadsheets/d/1JExAf_sUkbn91zDksYt8idEo6TW_NepBZD2cEvizy0o/edit?usp=sharing
- [x] MacBook Pro with external network @oterral

**Comment by gjn** [comment]
Added points from https://github.com/geoadmin/mf-geoadmin3/issues/2939

**Comment by gjn** [comment]
layersconfig is not a must (should)

optimiez bg layers already done, IMO, or is there more?

**Comment by ltclm** [comment]
2 1/2 BG Layer size has been reduced with lossy jpeg compression.
concerning WMS/PG Cluster:
what is the expected load?
5x, 10x, 100x of what we have now?

**Comment by cedricmoullet** [comment]
WMS / PG cluster: factor 2

**Comment by mariokeusen** [comment]
Working on the Abnahmen...

**Comment by mariokeusen** [comment]
Protocols sent to customers. Waiting for feedback/signatures

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-geoadmin3/pull/2953

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-geoadmin3/pull/2955

**Comment by ltclm** [comment]
pg cluster does not need an upgrade, the average load is 0.5 (= doing nothing), today a tile generation with 64 threads was using pg.bgdi.ch by mistake, the average load increased to 2.5 (=doing something). the 64 threads generated about 70 database queries / second.

**Comment by hpchrist** [comment]
I agree with that.

**Comment by gjn** [comment]
One could say that pg cluster is now over-dimensioned. ;=)

**Comment by hpchrist** [comment]
Hi,

we (infra team) think, that it's not needed to increase the varnish cluster. The current setup is already over-dimensioned. And adding a new varnish is less then an hour of work, if needed.

Regarding the billing monitoring: 
I've now added 3 alarms: one will monitor the montly costs of S3, the other the monthly costs of AWS Data Transfer and the third the total AWS charges.

**Comment by davidoesch** [comment]
@AFoletti can you translate msgid 3d_overlay_warning in IT? Thanks

**Comment by AFoletti** [comment]
Done.
Why do we write about 3D? It's not 3D. It's 25/10D ;)

**Comment by davidoesch** [comment]
Comes from official Komm ... #nuffsaid

**Comment by davidoesch** [comment]
https://share.pingdom.com/banners/91d47e31 for the mapproxy repsonse time (! updated every 24h!)

**Comment by mariokeusen** [comment]
Signed protocols will be on my desk tomorrow. Abnahme terrain and 2.5d-swissmaps TLM considered as done...

**Comment by gjn** [comment]
@davidoesch @cedricmoullet Can you confirm that current help is ok? (Should work on integration)

**Comment by davidoesch** [comment]
yes it is ok, I just added move left/right arrows to it.
http://help.geo.admin.ch/?id=28&lang=en

we do adaption fro SHIFT +arrow for tilt later on

**Comment by gjn** [comment]
Well done, everybody.
