### ISSUE TITLE
[MVT] iOS issues

### ISSUE THREAD

**Issue by boecklic** [geoadmin/mf-geoadmin3#4924]
This is a "container-issue" for all iOS related issue, which seem to be related to a safari bug in iOS 12.X which is known [@openlayers](https://github.com/openlayers/openlayers/issues/9291)

connected issues for mf-geoadmin are
- [x] [[MVT] switching styles crashing ](https://github.com/geoadmin/mf-geoadmin3/issues/4919)
- [x] [[MVT] floating labels](https://github.com/geoadmin/mf-geoadmin3/issues/4916)
- [x] [[MVT] Iphone X /macBookPro crash on load](https://github.com/geoadmin/mf-geoadmin3/issues/4912)

**Comment by pakb** [comment]
We also had feedback that the app was not loading on an iPad (or was in a permanent reload cycle), we need to find a way to reproduce this in house if we want to fix it.

**Comment by pakb** [comment]
all issues related to this topic have been fixed by using Mapbox render engine, I'm closing this

**Comment by ahocevar** [comment]
For what it's worth, openlayers/openlayers#9584 fixes the iOS issue (which you will still be running into for arbitrary maps with many layers).
