### ISSUE TITLE
use offset=0 in profile and use d3 smoothing features instead

### ISSUE THREAD

**Issue by danduk82** [geoadmin/mf-geoadmin3#4944]
**as:** a user
**I want:** a better estimation of hicking time and kml length in the profile window
**because:** I am always complaining about it

MUST have:
- [ ] mf-geoadmin3 should request service-alti with paramter `offset=0`
- [ ] must be related with [this issue in service-alti](https://github.com/geoadmin/service-alti/issues/42) so that the points digitized by the user can be displayed in the profile
- [ ] use _d3_ for smoothing, because smoothing looks good

CAN have:
- [ ] request service-alti at maximal possible resolution [once it is implemented](https://github.com/geoadmin/service-alti/issues/43)

**Comment by davidoesch** [comment]
Related to https://github.com/geoadmin/service-alti/issues/43

**Comment by davidoesch** [comment]
Related to https://github.com/geoadmin/service-alti/issues/42

**Comment by boecklic** [comment]
@boecklic commented: Related to https://github.com/geoadmin/service-alti/issues/43

**Comment by boecklic** [comment]
@boecklic commented: Related to https://github.com/geoadmin/service-alti/issues/42
